#!/bin/bash


# Display script instructions
echo "DO NOT RUN INSIDE THE INSTALL SHELL" & sleep 0.5
echo "MAKE SURE YOU ARE RUNNING THIS SCRIPT INSIDE THE NEW ROOT DIRECTORY" & sleep 0.5
echo "RUNNING THIS ON A LIVE SYSTEM WILL DESTROY IT, INCLUDING THE ISO INSTALLER ROOT DIRECTORY" & sleep 0.5
echo & sleep 0.5
echo "ABSOLUTELY BE SURE YOU HAVE USED ARCH-CHROOT AND THIS SCRIPT IS RUNNING IN THE NEW RESULTING SYSTEM ROOT DIRECTORY" & sleep 0.5
echo "YOU HAVE BEEN WARNED..." & sleep 0.5
echo & sleep 0.5

clear

# Main script variables
echo "Setting up main script variables" & sleep 0.5 

clear

## BELOW ARE THE VARIABLES WHICH ARE TO BE MODIFIED TO SUIT YOUR RESULT SYSTEM PREFERENCES, (Edit the strings before &&)
# Set the default username
DEFAULT_USER_990="syntax990"
echo "Setting default username to: $DEFAULT_USER_990"
sleep 0.5

# Set the final hostname
FINAL_HOSTNAME_990="SYN-TESTBUILD"
echo "Setting final hostname to: $FINAL_HOSTNAME_990"
sleep 0.5

# Set the locale generation
LOCALE_GEN_990="en_GB.UTF-8 UTF-8"
echo "Setting locale generation to: $LOCALE_GEN_990"
sleep 0.5

# Set the locale configuration
LOCALE_CONF_990="LANG=en_GB.UTF-8"
echo "Setting locale configuration to: $LOCALE_CONF_990"
sleep 0.5

# Set the zone information
ZONE_INFO990="GB"
echo "Setting zone information to: $ZONE_INFO990"
sleep 0.5

# Set the default shell choice
SHELL_CHOICE_990="/bin/zsh"
echo "Setting default shell choice to: $SHELL_CHOICE_990"
sleep 0.5

# Set the network interface
NETWORK_INTERFACE_990=$(ip -o -4 route show to default | awk '{print $5}')
echo "Setting network interface to: $NETWORK_INTERFACE_990"
sleep 0.5

# Set hardware clock to system time
echo "Setting hardware clock to system time"
hwclock --systohc
sleep 0.5

# Display configuration settings
echo
echo "Configuration settings:"
echo " - Username: $DEFAULT_USER_990"
sleep 0.5
echo " - Hostname: $FINAL_HOSTNAME_990"
sleep 0.5
echo " - Locale: $LOCALE_GEN_990"
sleep 0.5
echo " - Hardware clock set"
sleep 0.5
echo " - Mirror list generated by Reflector"
sleep 0.5
echo

# Generate various system variables
echo "Generating system variables"
sleep 0.5

echo "Removing existing locale.gen file" & rm /etc/locale.gen & sleep 0.5

echo "Creating new locale.gen file with locale generation"
touch /etc/locale.gen && echo "$LOCALE_GEN_990" >> /etc/locale.gen
locale-gen
sleep 0.5

echo "Creating new locale.conf file with locale configuration"
touch /etc/locale.conf && echo "$LOCALE_CONF_990" >> /etc/locale.conf
sleep 0.5

echo "Creating new hostname file with final hostname"
touch /etc/hostname && echo "$FINAL_HOSTNAME_990" >> /etc/hostname
sleep 0.5

echo "Creating symbolic link for timezone information"
ln -sf "/usr/share/zoneinfo/$ZONE_INFO990" /etc/localtime
sleep 0.5

# Modify sudoers file to allow members of the wheel group to use sudo
echo "Modifying sudoers file"
sleep 0.5

touch /etc/sudoers.d/990_wheel
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers.d/990_wheel
chmod 440 /etc/sudoers.d/990_wheel
sleep 0.5

# Create the user based on the variables, assign them a default shell, and take ownership of home directory and files
echo "Creating user account"
sleep 0.5

useradd -m -G wheel -s "$SHELL_CHOICE_990" "$DEFAULT_USER_990"
passwd "$DEFAULT_USER_990"
chown "$DEFAULT_USER_990:$DEFAULT_USER_990" -R "/home/$DEFAULT_USER_990"
sleep 0.5

# Enable systemd services for DHCP, WiFi, and set up the bootloader
echo "Enabling systemd services and setting up bootloader"
sleep 0.5

systemctl enable "dhcpcd@$NETWORK_INTERFACE_990.service"
systemctl enable iwd.service
bootctl --path=/boot install
sleep 0.5

# Display final instructions
echo
echo "Congratulations! You have successfully installed SYN-OS."
sleep 0.5
echo "Please ensure that your computer's BIOS/UEFI or Virtual Machine is configured to boot from the newly installed disk."
sleep 0.5
echo "After verifying the boot configuration, you can now exit and reboot to start using SYN-OS."
sleep 0.5
echo
echo
