#!/bin/sh
# runit stage 2: supervise every service linked into /var/service.
# Enable a service:  ln -s /etc/sv/NAME /var/service/
PATH=/usr/bin:/usr/sbin
exec env - PATH=$PATH runsvdir -P /var/service 'log: ...........................................................................................................'
