#!/bin/bash
source /syn-stage0.zsh
clear

# Main script variables
echo "Setting up new system variables" & sleep 0.2 

## BELOW ARE THE VARIABLES WHICH ARE TO BE MODIFIED TO SUIT YOUR RESULT SYSTEM PREFERENCES, (Edit the strings before &&)

# Set the default username
DEFAULT_USER_990="syntax990"
echo "Setting default username to: $DEFAULT_USER_990"
sleep 0.2

# Set the final hostname
FINAL_HOSTNAME_990="SYN-TESTBUILD"
echo "Setting final hostname to: $FINAL_HOSTNAME_990"
sleep 0.2

# Set the locale generation
LOCALE_GEN_990="en_GB.UTF-8 UTF-8"
echo "Setting locale generation to: $LOCALE_GEN_990"
sleep 0.2

# Set the locale configuration
LOCALE_CONF_990="LANG=en_GB.UTF-8"
echo "Setting locale configuration to: $LOCALE_CONF_990"
sleep 0.2

# Set the zone information
ZONE_INFO990="GB"
echo "Setting zone information to: $ZONE_INFO990"
sleep 0.2

# Set the default shell choice
SHELL_CHOICE_990="/bin/zsh"
echo "Setting default shell choice to: $SHELL_CHOICE_990"
sleep 0.2

# Set the network interface
NETWORK_INTERFACE_990=$(ip -o -4 route show to default | awk '{print $5}')
echo "Setting network interface to: $NETWORK_INTERFACE_990"
sleep 0.2

# Set hardware clock to system time
echo "Setting hardware clock to system time"
hwclock --systohc
sleep 0.2

# Display configuration settings
echo
echo "Configuration settings:"
echo " - Username: $DEFAULT_USER_990"
sleep 0.2
echo " - Hostname: $FINAL_HOSTNAME_990"
sleep 0.2
echo " - Locale: $LOCALE_GEN_990"
sleep 0.2
echo " - Hardware clock set"
sleep 0.2
echo " - Mirror list generated by Reflector"
sleep 0.2
echo

# Generate various system variables
echo "Generating system variables"
sleep 0.2

# Remove any garbled data or prematurley created locale.gen
echo "Removing existing locale.gen file"
rm /etc/locale.gen

echo "Creating new locale.gen file with locale generation"
touch /etc/locale.gen && echo "$LOCALE_GEN_990" >> /etc/locale.gen
locale-gen
sleep 0.2

echo "Creating new locale.conf file with locale configuration"
touch /etc/locale.conf && echo "$LOCALE_CONF_990" >> /etc/locale.conf
sleep 0.2

echo "Creating new hostname file with final hostname"
touch /etc/hostname && echo "$FINAL_HOSTNAME_990" >> /etc/hostname
sleep 0.2

echo "Creating symbolic link for timezone information"
ln -sf "/usr/share/zoneinfo/$ZONE_INFO990" /etc/localtime
sleep 0.2

# Modify sudoers file to allow members of the wheel group to use sudo
echo "Modifying sudoers file"
sleep 0.2

touch /etc/sudoers.d/990_wheel
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers.d/990_wheel
chmod 440 /etc/sudoers.d/990_wheel
sleep 0.2

# Create the user based on the variables, assign them a default shell, and take ownership of home directory and files
echo "Creating user account"
sleep 0.2

useradd -m -G wheel -s "$SHELL_CHOICE_990" "$DEFAULT_USER_990"
passwd "$DEFAULT_USER_990"
chown "$DEFAULT_USER_990:$DEFAULT_USER_990" -R "/home/$DEFAULT_USER_990"
sleep 0.2

# Enable systemd services for DHCP, WiFi, and set up the bootloader
echo "Enabling systemd services and setting up bootloader"
sleep 0.2

systemctl enable "dhcpcd@$NETWORK_INTERFACE_990.service"
systemctl enable iwd.service

# Install and configure the bootloader (systemd-boot)
echo "Installing and configuring bootloader (systemd-boot)"

bootctl --path=/boot install
ROOT_REAL_UUID_990=$(blkid -s UUID -o value $ROOT_PART_990)

echo "default syn.conf" >> /boot/loader/loader.conf
echo "timeout 0" >> /boot/loader/loader.conf
echo "editor 0" >> /boot/loader/loader.conf

echo "title   SYN-OS" >> /boot/loader/entries/syn.conf
echo "linux   /vmlinuz-linux" >> /boot/loader/entries/syn.conf
echo "initrd  /initramfs-linux.img" >> /boot/loader/entries/syn.conf
echo "options root=UUID=$ROOT_REAL_UUID_990 rw" >> /boot/loader/entries/syn.conf

# Write the mkinitcpio data to ensure the system has the neccessary hooks to decrypt itself
echo 'HOOKS=(base udev modconf kms memdisk encrypt block filesystems keyboard)' >> /etc/mkinitcpio.conf

sleep 0.2

echo "                                                                                                                       
████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                       
                                                                                              ██
  ██████▓██   ██▓ ███▄    █  ▒█████    ██████                                                 ██
▒██    ▒ ▒██  ██▒ ██ ▀█   █ ▒██▒  ██▒▒██    ▒                                                 ██
░ ▓██▄    ▒██ ██░▓██  ▀█ ██▒▒██░  ██▒░ ▓██▄                                                   ██
  ▒   ██▒ ░ ▐██▓░▓██▒  ▐▌██▒▒██   ██░  ▒   ██▒      ______ _  _  _ _   _        _________     ██
▒██████▒▒ ░ ██▒▓░▒██░   ▓██░░ ████▓▒░▒██████▒▒      \  ___) || || | \ | |      / _ \  ___)    ██
▒ ▒▓▒ ▒ ░  ██▒▒▒ ░ ▒░   ▒ ▒ ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░       \ \  | \| |/ |  \| |_____| | | \ \       ██
░ ░▒  ░ ░▓██ ░▒░ ░ ░░   ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░        > >  \_   _/|     (_____) | | |> >      ██
░  ░  ░  ▒ ▒ ░░     ░   ░ ░ ░ ░ ░ ▒  ░  ░  ░         / /__   | |  | |\  |     | |_| / /__     ██
      ░  ░ ░              ░     ░ ░        ░        /_____)  |_|  |_| \_|      \___/_____)    ██
         ░ ░                                                                                  ██
                                                                                              ██
                          01010011 01011001 01001110 00101101 01001111 01010011               ██
                                                                                              ██
                                           SYN-OS: The Syntax Operating System                ██
 ####  #### #   #      ###   ####                                                             ██
#     #   # #   #     #   # #                                                                 ██
#      #### ##### ### #   # #              Created By: ----¬                                  ██
#      #  # #   #     #   # #                              :                                  ██
 #### #   # #   #      ###   ####                          :                                  ██
                                                          ===                                 ██
                                                                                              ██
███████ ██    ██ ███    ██ ████████  █████  ██   ██  █████   █████   ██████                   ██
██       ██  ██  ████   ██    ██    ██   ██  ██ ██  ██   ██ ██   ██ ██  ████                  ██
███████   ████   ██ ██  ██    ██    ███████   ███    ██████  ██████ ██ ██ ██                  ██
     ██    ██    ██  ██ ██    ██    ██   ██  ██ ██       ██      ██ ████  ██                  ██
███████    ██    ██   ████    ██    ██   ██ ██   ██  █████   █████   ██████                   ██
                                                                                              ██
████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                                                                                                                                     
    "

# Display final instructions
echo
echo "SUMMARY: Stage One Complete, Congratulations! You have successfully installed SYN-OS."
sleep 1
echo "Please ensure that your computer's BIOS/UEFI or Virtual Machine is configured to boot from the newly installed disk."
sleep 1
echo "After verifying the boot configuration, you can now exit and reboot to start using SYN-OS."
sleep 1
echo
echo
